### ISSUE TITLE
Investigate turbolinks & google analytics

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#651]
https://github.com/turbolinks/turbolinks/issues/75#issuecomment-255867311

May / may not be working. Comment would indicate its shouldn't, but haven't seen a huge drop in GA hits:

![image](https://cloud.githubusercontent.com/assets/1690934/19665170/a036a6c4-9a3b-11e6-9e39-a97c5242ee18.png)

---

Hmm, looking at pageviews... maybe?

![image](https://cloud.githubusercontent.com/assets/1690934/19665191/bf7c0ad8-9a3b-11e6-9207-0391d6ec7e2d.png)

**Comment by aguynamedben** [comment]
(I'm the writer of the comment linked in #75)

I'm not seeing anything where Turbolinks breaks Google Analytics outright (see [relevant Google Analytics docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications)).

Because Turbolinks is inadvertently hijacking clicks on same-page anchor links (see #75), 'turbolinks:load' fires during simple intra-page navigation (i.e. clicking a Table of Contents link), and if 'turbolinks:load' is used to track pageviews, you could see increased pageviews for those pages (not lower as you mention, not sure what your graphs are of).

I don't necessarily think my comment on the other issue warrants a new issue on its own, I was just noting a potentially common side effect of the same-page anchor link behavior.

**Comment by wjdp** [comment]
I think I was mixing things up while reading issues at 11pm. GA on our site is in a `<script>` at the bottom of the body so should be running on every pageload through turbolinks.

Thanks very much for the follow up!

**Comment by aguynamedben** [comment]
@wjdp One other thing to consider that I just noticed today using Google Analytics and putting things in <body> with Turbolinks 5...

It appears raw JavaScript in the <body> tag can be executed twice. 1st - when your doing a Turbolinks visit and the page is loaded out of the Turbolinks cache. 2nd - when the background fetch of the page completes and the cached page in the DOM is replaced with the new version of the page that was fetched in the background. In my (new) experience, the JavaScript is re-run at that point. So make sure you use console.log messages to sanity check. Godspeed.

**Comment by glennfu** [comment]
I've had good success here by adding the autotrack (https://github.com/googleanalytics/autotrack) plugin and having these enabled:
```
  ga('require', 'cleanUrlTracker');
  ga('require', 'eventTracker');
  ga('require', 'urlChangeTracker');
  ga('require', 'pageVisibilityTracker');
```

With that I've been able to get tracking that seems accurate to me. It seems much better suited for automatically figuring out how to deal with SPA-like scenarios.

**Comment by wjdp** [comment]
@aguynamedben That makes sense, thanks for pointing it out!
@glennfu Hadn't heard of autotrack before, looks very useful. Shall investigate.

**Comment by wjdp** [comment]
No further action needed
