### ISSUE TITLE
Improve layout of 'Publicity Materials'

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#726]
Any way they could utilise screen space better than they currently do??
![publicity material issue](https://cloud.githubusercontent.com/assets/14825903/23553066/e3c1add0-0016-11e7-866a-dc1ae360bb4a.PNG)

**Comment by davidtaylorhq** [comment]
Could just do a collapsing thing like the smugmug albums

**Comment by nhyty** [comment]
not sure how that would work with pdfs etc though

**Comment by samozzy** [comment]
Would a floating table of contents be useful?

**Comment by wjdp** [comment]
It would be nice to 're-imagine' this section. Unsure if collapsing or another method would be best. Needs playing around with really.

Can't find an issue but this ties in with trying to evolve the design of the top section of show pages.

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/24077318/3ac9a822-0c41-11e7-8873-13d6cf3e0407.png)

Unsure if this uses the space better but I've made all items have backgrounds so they fill the space better (rather than just a jumble of different size images, which can happen)

On desktop I'd potentially look at spilling over into 'poster column'. This works on some pages, (DEAD yes, [Pillowman](https://history.newtheatre.org.uk/years/12_13/the_pillowman/) no)

I'm happy with the vertical space usage, scrolling is OK.

Other thoughts welcome!

**Comment by davidtaylorhq** [comment]
I like the backgrounds, but they really need more contrast from the page background - I can barely see them on my macbook screen, or my rubbishy samsung screen.

Re. moving across to the poster column, I think it's a lot of potential layout breakage for not a lot of benefit... but if there's an easy way to do it then why not.

**Comment by wjdp** [comment]
Backgrounds on images were supposed to be subtle :smile: I've lightened them a little along with the video ones (image colour was just a greyscale of the page background, so wasn't any contrast there at all)

**Comment by wjdp** [comment]
Merge any remaining points into #672
