### ISSUE TITLE
Assistant Director Icon

### ISSUE THREAD

**Issue by davidtaylorhq** [newtheatre/history-project#804]
Assistant director should get director icon as well

For example:
https://history.newtheatre.org.uk/years/94_95/westside_story/

<img width="579" alt="screen shot 2017-04-19 at 15 57 20" src="https://cloud.githubusercontent.com/assets/6270921/25186711/e40d7bf8-2518-11e7-9da0-4ef2b2cdc6f9.png">

**Comment by samozzy** [comment]
Related: Should 'Shadow X' get the same icon as 'X'? (Shadow TDs currently do not, for instance)

**Comment by wjdp** [comment]
Feel free to spin up a PR addressing this. If you browse through shows I'm sure there's more inconsistencies. 

Icon settings are in a `_data/` file, `role-icons` I think

**Comment by samozzy** [comment]
Will do. Just wanted to make sure there was agreement first!

**Comment by wjdp** [comment]
Unsure where the discussion was but all 'roles' should be in the form `Director`, `Designer`. Just had a look at the file, seems other forms eg. `Design` are put as `aliases` to account for inconsistencies.

**Comment by samozzy** [comment]
Is there any scope for wildcards here? Eg, *Lighting* gets a lightbulb, to account for Shadow, Designer, Assistant, etc.

**Comment by wjdp** [comment]
@samozzy It used to be a liquid template that did the matching, think it's a plugin now, so yeah probably.

**Comment by wjdp** [comment]
@samozzy Nope it's still done in liquid: https://github.com/newtheatre/history-project/blob/master/_includes/person_list.html#L53. In order to do wildcards we should move this to ruby. However I'd forsee issues where we get matches where we didn't want them so would lean towards just putting shadow &c into aliases on the role file: https://github.com/newtheatre/history-project/blob/master/_data/roles.yaml
